include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:

  exclude:
    - test/mock_packages/**
  errors:

    unused_import: warning

    unawaited_futures: ignore

linter:
  rules:
    - await_only_futures
    - avoid_single_cascade_in_expression_statements
    - depend_on_referenced_packages
    - empty_statements
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - prefer_initializing_formals
    - prefer_typing_uninitialized_variables
    - unnecessary_brace_in_string_interps
    - unnecessary_overrides
    - unnecessary_parenthesis
    - void_checks